baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Loose Thoughts Collected"
theme = 'hermit-v2'

# more config options exemplified at
# https://github.com/1bl4z3r/hermit-V2/blob/main/hugo.toml.example
# https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/

[markup]
 [markup.goldmark]
   [markup.goldmark.extensions]
     [markup.goldmark.extensions.passthrough]
       enable = true
       [markup.goldmark.extensions.passthrough.delimiters]
         block = [['\[', '\]'], ['$$', '$$']]
         inline = [['\(', '\)'], ['$', '$']]

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "Becker Awqatty's public brainscape"
  gitUrl = "https://github.com/CrepeGoat/blog/tree/main"
  enableGitInfo = true
  global_mathjax = true
  math = true

  readTime = true
  shareSocial = true

  [params.author]
    name = "BekR"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/CrepeGoat/blog/tree/main"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/beckerawqatty/"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
